# .github/workflows/main.yml
name: Norminette + Tests
on: [push, pull_request]

jobs:
  norminette_v3_job:
    runs-on: ubuntu-latest
    name: norminette v3
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
  minishell_tester:
    runs-on: ubuntu-latest
    name: minishell-tester
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.10.12
      - uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: LucasKuhn/minishell_tester
          path: minishell_tester
      - name: Build and copy lib
        run: make re && sudo cp libft.so /usr/local/lib && sudo ldconfig
      - name: Run the tests
#        run: cd minishell_tester && ./tester
        run: |
          result=$(cd minishell_tester && (./tester || true) | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' | tail -n 2 | head -n 1)
          passed=$(echo $result | cut -d'/' -f1)
          total=$(echo $result | cut -d'/' -f2)
          percentage=$(( (100 * passed) / total ))
          echo "$result ($percentage)" > percentage
          if [ $percentage -lt 80 ]; then
            exit 1
          fi
          echo "$percentage%"
          exit 0
      - name: Percentage badge
        with:
          passed: ${{ job.status == 'success' }}
        run: |
          result=$(cat percentage | jq -sRr @uri)
          if [ $passed ]; then
            color="green"
          else
            color="red"
          fi
          url="https://badgen.net/badge/Tests%20passed/$result/$color"
          wget -O percentage.svg $url
      - name: Upload badge
        uses: actions/upload-artifact@v2
        with:
          name: percentage
          path: percentage.svg